
buildscript {
    repositories {
        // 作为 Xposed 模块使用务必添加，其它情况可选
        maven { url 'https://api.xposed.info/' }
        // MavenCentral 有 2 小时缓存，若无法集成最新版本请添加此地址
        maven { url 'https://s01.oss.sonatype.org/content/repositories/releases/' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google/'}
        maven { url 'https://maven.aliyun.com/repository/jcenter/'}
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.0'
        classpath "org.jetbrains.kotlin:kotlin-stdlib:2.1.10"
    }
}

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google/'}
        maven { url 'https://maven.aliyun.com/repository/jcenter/'}
        google()
        mavenCentral()
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete project.layout.buildDirectory
}